# Generated by Django 3.2.5 on 2021-11-23 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusotmer_name', models.CharField(help_text='Fortune Makers', max_length=120)),
                ('address', models.CharField(help_text='106 Ar Riyadh Aveneu', max_length=120)),
                ('supplier_Terms', models.CharField(max_length=200)),
                ('supplier_Contac_Name', models.CharField(max_length=200)),
                ('mobile_no', models.IntegerField(default=123, help_text='0505652039')),
                ('land_Line', models.IntegerField(default=123, help_text='096611-2335464')),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_Date', models.DateField(auto_now=True)),
                ('department', models.CharField(help_text='Finance', max_length=80)),
                ('total_Ammount', models.FloatField(default=0, verbose_name='Total')),
                ('vat', models.FloatField(default=15, verbose_name='Vat Percentage %')),
                ('total_Vat', models.FloatField(default=0, verbose_name='Vat Ammount')),
                ('terms', models.CharField(blank=True, max_length=300, verbose_name='Terms of Payment')),
                ('comments', models.CharField(blank=True, max_length=300, verbose_name='Comments')),
                ('cusotmer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.customers')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_Number', models.CharField(blank=True, help_text='item-001', max_length=30, verbose_name='Reference No')),
                ('item_Name', models.CharField(help_text='Paper Cups grey', max_length=60, verbose_name='Items')),
                ('item_detail', models.CharField(help_text='Paper Cups grey', max_length=120, verbose_name='Item Details')),
                ('item_date_created', models.DateField(auto_now_add=True, help_text='Date when item was created', verbose_name='Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='invoice_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.IntegerField(default=0, help_text='200')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('total_price', models.IntegerField(default=0, help_text='item_price * item quantity', verbose_name='Total Ammount')),
                ('total_vat', models.IntegerField(default=0, help_text='200', verbose_name='Vat')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.invoice')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.items')),
            ],
        ),
    ]
