# Generated by Django 3.2.5 on 2021-11-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_Name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='item_Number',
            new_name='item_number',
        ),
        migrations.AlterField(
            model_name='items',
            name='item_detail',
            field=models.CharField(blank=True, help_text='Paper Cups grey', max_length=120, verbose_name='Item Details'),
        ),
    ]
