# Generated by Django 3.2.9 on 2021-12-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_rename_cusotmer_name_invoice_cusotmer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='mobile_no',
            field=models.IntegerField(default=123, help_text='0505050505'),
        ),
    ]
