# Generated by Django 4.0.3 on 2022-06-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_invoice_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedescription',
            name='total_line_value',
            field=models.IntegerField(default=0, help_text='200', verbose_name='Vat'),
        ),
    ]
