# Generated by Django 4.0.3 on 2022-06-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_invoicedescription_total_line_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=80)),
                ('vat', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=40)),
                ('iban', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
