# Generated by Django 4.0.3 on 2022-06-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='zacta_API_Key',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
