# Generated by Django 4.0.3 on 2022-06-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_company_zacta_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='zacta_API_Key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_number',
            field=models.IntegerField(blank=True, help_text='item-001', max_length=30, verbose_name='Reference No'),
        ),
    ]
