# Generated by Django 4.0.3 on 2022-07-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_alter_company_phone_alter_company_zacta_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_number',
            field=models.IntegerField(blank=True, help_text='item-001', verbose_name='Item Number'),
        ),
    ]
